require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SegurosController do

  # This should return the minimal set of attributes required to create a valid
  # Seguro. As you add validations to Seguro, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SegurosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all seguros as @seguros" do
      seguro = Seguro.create! valid_attributes
      get :index, {}, valid_session
      assigns(:seguros).should eq([seguro])
    end
  end

  describe "GET show" do
    it "assigns the requested seguro as @seguro" do
      seguro = Seguro.create! valid_attributes
      get :show, {:id => seguro.to_param}, valid_session
      assigns(:seguro).should eq(seguro)
    end
  end

  describe "GET new" do
    it "assigns a new seguro as @seguro" do
      get :new, {}, valid_session
      assigns(:seguro).should be_a_new(Seguro)
    end
  end

  describe "GET edit" do
    it "assigns the requested seguro as @seguro" do
      seguro = Seguro.create! valid_attributes
      get :edit, {:id => seguro.to_param}, valid_session
      assigns(:seguro).should eq(seguro)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Seguro" do
        expect {
          post :create, {:seguro => valid_attributes}, valid_session
        }.to change(Seguro, :count).by(1)
      end

      it "assigns a newly created seguro as @seguro" do
        post :create, {:seguro => valid_attributes}, valid_session
        assigns(:seguro).should be_a(Seguro)
        assigns(:seguro).should be_persisted
      end

      it "redirects to the created seguro" do
        post :create, {:seguro => valid_attributes}, valid_session
        response.should redirect_to(Seguro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved seguro as @seguro" do
        # Trigger the behavior that occurs when invalid params are submitted
        Seguro.any_instance.stub(:save).and_return(false)
        post :create, {:seguro => {}}, valid_session
        assigns(:seguro).should be_a_new(Seguro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Seguro.any_instance.stub(:save).and_return(false)
        post :create, {:seguro => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested seguro" do
        seguro = Seguro.create! valid_attributes
        # Assuming there are no other seguros in the database, this
        # specifies that the Seguro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Seguro.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => seguro.to_param, :seguro => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested seguro as @seguro" do
        seguro = Seguro.create! valid_attributes
        put :update, {:id => seguro.to_param, :seguro => valid_attributes}, valid_session
        assigns(:seguro).should eq(seguro)
      end

      it "redirects to the seguro" do
        seguro = Seguro.create! valid_attributes
        put :update, {:id => seguro.to_param, :seguro => valid_attributes}, valid_session
        response.should redirect_to(seguro)
      end
    end

    describe "with invalid params" do
      it "assigns the seguro as @seguro" do
        seguro = Seguro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Seguro.any_instance.stub(:save).and_return(false)
        put :update, {:id => seguro.to_param, :seguro => {}}, valid_session
        assigns(:seguro).should eq(seguro)
      end

      it "re-renders the 'edit' template" do
        seguro = Seguro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Seguro.any_instance.stub(:save).and_return(false)
        put :update, {:id => seguro.to_param, :seguro => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested seguro" do
      seguro = Seguro.create! valid_attributes
      expect {
        delete :destroy, {:id => seguro.to_param}, valid_session
      }.to change(Seguro, :count).by(-1)
    end

    it "redirects to the seguros list" do
      seguro = Seguro.create! valid_attributes
      delete :destroy, {:id => seguro.to_param}, valid_session
      response.should redirect_to(seguros_url)
    end
  end

end
